const errorCode = {
  501: "user is not authorized to perform this action",
  502: "Not allowed by CORS",
  503: "Url not found",
  504: "password must contain digit",
  505: "Sonething wents wrong!",
  506: "please enter correct email_id",
  507: "UserId is already exist!",
  508: "Please Resend the OTP",
  509: "Please enter currect OTP",
  510: "email / UserId exists!",
  511: "email / UserId doesn't exist!",
  512: "please enter correct password",
  513: "Please enter any one data",
  514: "Please enter the secrect key",
  515: "User type is required",
  516: "Refresh token is required",
  517: "Internal server error",
  518: "Not Available",
  519: "Auth Expired",
  520: "Data is not available!",
  521: "Application is already present.",
  522: "Post is not available!",
  523: "Please provide a correct option!",
  524: "This user ID can't be referred!",
  525: "This user is logged out! Please log in again.",
  526: "Your review is already present.",
  527: "User Detais missing.",
  528: "You can't review yourself.",
  529: "User can't create more than one tag.",
  530: "You can't book yourself.",
  531: "Not Valid",
  532: "OTP limit exceeded, Please try again after 15 mins.",
  533: "You can't change the status.",
  534: "Refresh token failed",
  535: "User verified. You can't change.",
  536: "Post limit reached.",
  537: "Application Blocked.",
  538: "Application Unblocked.",
};
const successCode = {
  201: "Data return seccessfully",
  202: "OTP Sent seccessfully",
  203: "Available",
  204: "Successfully Saved",
  205: "Successfully Created",
  206: "Successfully deleted",
  207: "Email Sent Seccessfully",
  208: "User loged out!",
};

module.exports = { errorCode, successCode };
